#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Holberton School" when queried
#++    at the root with a curl GET request.

sudo apt-get update
sudo apt-get install -y nginx

mkdir /var/www/html
touch /var/www/html/index.html
echo "Holberton School" > /var/www/html/index.html
sudo service ngix start
