#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Holberton School" when queried
#++    at the root with a curl GET request

sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Verify if Nginx is installed successfully
if [ "$(dpkg-query -W -f='${Status}' nginx 2>/dev/null | grep -c "ok installed")" -eq 0 ]; then
    echo "Installation failed. Exiting."
    exit 1
fi

# Configure Nginx to listen on port 80
sudo sed -i 's/\(listen 80;\)/\1 default_server;/' /etc/nginx/sites-available/default

# Restart Nginx without using systemctl
sudo service nginx restart
