#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Holberton School" when queried
#++    at the root with a curl GET request

sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Verify if Nginx is installed successfully
sudo ufw allow 'Nginx HTTP'

echo "Holberton School" | sudo tee /var/www/html/index.html

sudo nginx -t
sudo nginx start
