#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"

sudo apt-get update
sudo apt-get install -y nginx


echo "Holberton School" | sudo tee /var/www/html/index.html

#using sed command to perform redirection 

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/\youtube.com\/watch?v=QH2-TGUlwu4 permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default


sudo service nginx restart
